insert into words (word,description) values ("sofia","Town In Bulgaria");
insert into words (word,description) values ("plovdiv","Town In Bulgaria");
insert into words (word,description) values ("varna","Town In Bulgaria");
insert into words (word,description) values ("burgas","Town In Bulgaria");
insert into words (word,description) values ("ruse","Town In Bulgaria");
insert into words (word,description) values ("stara zagora","Town In Bulgaria");
insert into words (word,description) values ("pleven","Town In Bulgaria");
insert into words (word,description) values ("dobrich","Town In Bulgaria");
insert into words (word,description) values ("sliven","Town In Bulgaria");
insert into words (word,description) values ("shumen","Town In Bulgaria");
insert into words (word,description) values ("pernik","Town In Bulgaria");
insert into words (word,description) values ("haskovo","Town In Bulgaria");
insert into words (word,description) values ("yambol","Town In Bulgaria");
insert into words (word,description) values ("pazardzhik","Town In Bulgaria");
insert into words (word,description) values ("blagoevgrad","Town In Bulgaria");
insert into words (word,description) values ("veliko tarnovo","Town In Bulgaria");
insert into words (word,description) values ("vratsa","Town In Bulgaria");
insert into words (word,description) values ("gabrovo","Town In Bulgaria");
insert into words (word,description) values ("asenovgrad","Town In Bulgaria");
insert into words (word,description) values ("vidin","Town In Bulgaria");
insert into words (word,description) values ("kazanlak","Town In Bulgaria");
insert into words (word,description) values ("kyustendil","Town In Bulgaria");
insert into words (word,description) values ("kardzhali","Town In Bulgaria");
insert into words (word,description) values ("montana","Town In Bulgaria");
insert into words (word,description) values ("dimitrovgrad","Town In Bulgaria");
insert into words (word,description) values ("targovishte","Town In Bulgaria");
insert into words (word,description) values ("lovech","Town In Bulgaria");
insert into words (word,description) values ("silistra","Town In Bulgaria");
insert into words (word,description) values ("dupnitsa","Town In Bulgaria");
insert into words (word,description) values ("svishtov","Town In Bulgaria");
insert into words (word,description) values ("razgrad","Town In Bulgaria");
insert into words (word,description) values ("gorna oryahovitsa","Town In Bulgaria");
insert into words (word,description) values ("smolyan","Town In Bulgaria");
insert into words (word,description) values ("petrich","Town In Bulgaria");
insert into words (word,description) values ("sandanski","Town In Bulgaria");
insert into words (word,description) values ("samokov","Town In Bulgaria");
insert into words (word,description) values ("sevlievo","Town In Bulgaria");
insert into words (word,description) values ("lom","Town In Bulgaria");
insert into words (word,description) values ("karlovo","Town In Bulgaria");
insert into words (word,description) values ("velingrad","Town In Bulgaria");
insert into words (word,description) values ("nova zagora","Town In Bulgaria");
insert into words (word,description) values ("troyan","Town In Bulgaria");
insert into words (word,description) values ("aytos","Town In Bulgaria");
insert into words (word,description) values ("botevgrad","Town In Bulgaria");
insert into words (word,description) values ("gotse delchev","Town In Bulgaria");
insert into words (word,description) values ("peshtera","Town In Bulgaria");
insert into words (word,description) values ("harmanli","Town In Bulgaria");
insert into words (word,description) values ("karnobat","Town In Bulgaria");
insert into words (word,description) values ("svilengrad","Town In Bulgaria");
insert into words (word,description) values ("panagyurishte","Town In Bulgaria");
insert into words (word,description) values ("chirpan","Town In Bulgaria");
insert into words (word,description) values ("popovo","Town In Bulgaria");
insert into words (word,description) values ("rakovski","Town In Bulgaria");
insert into words (word,description) values ("radomir","Town In Bulgaria");
insert into words (word,description) values ("novi iskar","Town In Bulgaria");
insert into words (word,description) values ("kozloduy","Town In Bulgaria");
insert into words (word,description) values ("parvomay","Town In Bulgaria");
insert into words (word,description) values ("berkovitsa","Town In Bulgaria");
insert into words (word,description) values ("cherven bryag","Town In Bulgaria");
insert into words (word,description) values ("pomorie","Town In Bulgaria");
insert into words (word,description) values ("ihtiman","Town In Bulgaria");
insert into words (word,description) values ("radnevo","Town In Bulgaria");
insert into words (word,description) values ("provadiya","Town In Bulgaria");
insert into words (word,description) values ("novi pazar","Town In Bulgaria");
insert into words (word,description) values ("razlog","Town In Bulgaria");
insert into words (word,description) values ("byala slatina","Town In Bulgaria");
insert into words (word,description) values ("nesebar","Town In Bulgaria");
insert into words (word,description) values ("balchik","Town In Bulgaria");
insert into words (word,description) values ("kostinbrod","Town In Bulgaria");
insert into words (word,description) values ("stamboliyski","Town In Bulgaria");
insert into words (word,description) values ("kavarna","Town In Bulgaria");
insert into words (word,description) values ("knezha","Town In Bulgaria");
insert into words (word,description) values ("pavlikeni","Town In Bulgaria");
insert into words (word,description) values ("mezdra","Town In Bulgaria");
insert into words (word,description) values ("etropole","Town In Bulgaria");
insert into words (word,description) values ("levski","Town In Bulgaria");
insert into words (word,description) values ("teteven","Town In Bulgaria");
insert into words (word,description) values ("elhovo","Town In Bulgaria");
insert into words (word,description) values ("bankya","Town In Bulgaria");
insert into words (word,description) values ("tryavna","Town In Bulgaria");
insert into words (word,description) values ("lukovit","Town In Bulgaria");
insert into words (word,description) values ("tutrakan","Town In Bulgaria");
insert into words (word,description) values ("sredets","Town In Bulgaria");
insert into words (word,description) values ("sopot","Town In Bulgaria");
insert into words (word,description) values ("byala","Town In Bulgaria");
insert into words (word,description) values ("veliki preslav","Town In Bulgaria");
insert into words (word,description) values ("isperih","Town In Bulgaria");
insert into words (word,description) values ("belene","Town In Bulgaria");
insert into words (word,description) values ("omurtag","Town In Bulgaria");
insert into words (word,description) values ("bansko","Town In Bulgaria");
insert into words (word,description) values ("krichim","Town In Bulgaria");
insert into words (word,description) values ("galabovo","Town In Bulgaria");
insert into words (word,description) values ("devnya","Town In Bulgaria");
insert into words (word,description) values ("septemvri","Town In Bulgaria");
insert into words (word,description) values ("rakitovo","Town In Bulgaria");
insert into words (word,description) values ("lyaskovets","Town In Bulgaria");
insert into words (word,description) values ("svoge","Town In Bulgaria");
insert into words (word,description) values ("aksakovo","Town In Bulgaria");
insert into words (word,description) values ("kubrat","Town In Bulgaria");
insert into words (word,description) values ("dryanovo","Town In Bulgaria");
insert into words (word,description) values ("beloslav","Town In Bulgaria");
insert into words (word,description) values ("pirdop","Town In Bulgaria");
insert into words (word,description) values ("lyubimets","Town In Bulgaria");
insert into words (word,description) values ("momchilgrad","Town In Bulgaria");
insert into words (word,description) values ("slivnitsa","Town In Bulgaria");
insert into words (word,description) values ("hisarya","Town In Bulgaria");
insert into words (word,description) values ("zlatograd","Town In Bulgaria");
insert into words (word,description) values ("kostenets","Town In Bulgaria");
insert into words (word,description) values ("devin","Town In Bulgaria");
insert into words (word,description) values ("general toshevo","Town In Bulgaria");
insert into words (word,description) values ("simeonovgrad","Town In Bulgaria");
insert into words (word,description) values ("simitli","Town In Bulgaria");
insert into words (word,description) values ("elin pelin","Town In Bulgaria");
insert into words (word,description) values ("dolni chiflik","Town In Bulgaria");
insert into words (word,description) values ("tervel","Town In Bulgaria");
insert into words (word,description) values ("dulovo","Town In Bulgaria");
insert into words (word,description) values ("varshets","Town In Bulgaria");
insert into words (word,description) values ("kotel","Town In Bulgaria");
insert into words (word,description) values ("madan","Town In Bulgaria");
insert into words (word,description) values ("straldzha","Town In Bulgaria");
insert into words (word,description) values ("saedinenie","Town In Bulgaria");
insert into words (word,description) values ("bobov dol","Town In Bulgaria");
insert into words (word,description) values ("tsarevo","Town In Bulgaria");
insert into words (word,description) values ("kuklen","Town In Bulgaria");
insert into words (word,description) values ("tvarditsa","Town In Bulgaria");
insert into words (word,description) values ("yakoruda","Town In Bulgaria");
insert into words (word,description) values ("elena","Town In Bulgaria");
insert into words (word,description) values ("topolovgrad","Town In Bulgaria");
insert into words (word,description) values ("bozhurishte","Town In Bulgaria");
insert into words (word,description) values ("chepelare","Town In Bulgaria");
insert into words (word,description) values ("oryahovo","Town In Bulgaria");
insert into words (word,description) values ("sozopol","Town In Bulgaria");
insert into words (word,description) values ("belogradchik","Town In Bulgaria");
insert into words (word,description) values ("perushtitsa","Town In Bulgaria");
insert into words (word,description) values ("zlatitsa","Town In Bulgaria");
insert into words (word,description) values ("strazhitsa","Town In Bulgaria");
insert into words (word,description) values ("krumovgrad","Town In Bulgaria");
insert into words (word,description) values ("kameno","Town In Bulgaria");
insert into words (word,description) values ("dalgopol","Town In Bulgaria");
insert into words (word,description) values ("vetovo","Town In Bulgaria");
insert into words (word,description) values ("suvorovo","Town In Bulgaria");
insert into words (word,description) values ("dolni dabnik","Town In Bulgaria");
insert into words (word,description) values ("dolna banya","Town In Bulgaria");
insert into words (word,description) values ("pravets","Town In Bulgaria");
insert into words (word,description) values ("nedelino","Town In Bulgaria");
insert into words (word,description) values ("polski trambesh","Town In Bulgaria");
insert into words (word,description) values ("trastenik","Town In Bulgaria");
insert into words (word,description) values ("bratsigovo","Town In Bulgaria");
insert into words (word,description) values ("koynare","Town In Bulgaria");
insert into words (word,description) values ("godech","Town In Bulgaria");
insert into words (word,description) values ("slavyanovo","Town In Bulgaria");
insert into words (word,description) values ("dve mogili","Town In Bulgaria");
insert into words (word,description) values ("kostandovo","Town In Bulgaria");
insert into words (word,description) values ("debelets","Town In Bulgaria");
insert into words (word,description) values ("strelcha","Town In Bulgaria");
insert into words (word,description) values ("sapareva banya","Town In Bulgaria");
insert into words (word,description) values ("ignatievo","Town In Bulgaria");
insert into words (word,description) values ("smyadovo","Town In Bulgaria");
insert into words (word,description) values ("breznik","Town In Bulgaria");
insert into words (word,description) values ("sveti vlas","Town In Bulgaria");
insert into words (word,description) values ("nikopol","Town In Bulgaria");
insert into words (word,description) values ("shivachevo","Town In Bulgaria");
insert into words (word,description) values ("belovo","Town In Bulgaria");
insert into words (word,description) values ("tsar kaloyan","Town In Bulgaria");
insert into words (word,description) values ("ivaylovgrad","Town In Bulgaria");
insert into words (word,description) values ("valchedram","Town In Bulgaria");
insert into words (word,description) values ("marten","Town In Bulgaria");
insert into words (word,description) values ("glodzhevo","Town In Bulgaria");
insert into words (word,description) values ("sarnitsa","Town In Bulgaria");
insert into words (word,description) values ("letnitsa","Town In Bulgaria");
insert into words (word,description) values ("varbitsa","Town In Bulgaria");
insert into words (word,description) values ("iskar","Town In Bulgaria");
insert into words (word,description) values ("ardino","Town In Bulgaria");
insert into words (word,description) values ("shabla","Town In Bulgaria");
insert into words (word,description) values ("rudozem","Town In Bulgaria");
insert into words (word,description) values ("vetren","Town In Bulgaria");
insert into words (word,description) values ("kresna","Town In Bulgaria");
insert into words (word,description) values ("banya","Town In Bulgaria");
insert into words (word,description) values ("batak","Town In Bulgaria");
insert into words (word,description) values ("maglizh","Town In Bulgaria");
insert into words (word,description) values ("valchi dol","Town In Bulgaria");
insert into words (word,description) values ("gulyantsi","Town In Bulgaria");
insert into words (word,description) values ("dragoman","Town In Bulgaria");
insert into words (word,description) values ("zavet","Town In Bulgaria");
insert into words (word,description) values ("kran","Town In Bulgaria");
insert into words (word,description) values ("miziya","Town In Bulgaria");
insert into words (word,description) values ("primorsko","Town In Bulgaria");
insert into words (word,description) values ("sungurlare","Town In Bulgaria");
insert into words (word,description) values ("dolna mitropoliya","Town In Bulgaria");
insert into words (word,description) values ("krivodol","Town In Bulgaria");
insert into words (word,description) values ("kula","Town In Bulgaria");
insert into words (word,description) values ("kalofer","Town In Bulgaria");
insert into words (word,description) values ("slivo pole","Town In Bulgaria");
insert into words (word,description) values ("kaspichan","Town In Bulgaria");
insert into words (word,description) values ("apriltsi","Town In Bulgaria");
insert into words (word,description) values ("belitsa","Town In Bulgaria");
insert into words (word,description) values ("roman","Town In Bulgaria");
insert into words (word,description) values ("dzhebel","Town In Bulgaria");
insert into words (word,description) values ("dolna oryahovitsa","Town In Bulgaria");
insert into words (word,description) values ("buhovo","Town In Bulgaria");
insert into words (word,description) values ("gurkovo","Town In Bulgaria");
insert into words (word,description) values ("pavel banya","Town In Bulgaria");
insert into words (word,description) values ("nikolaevo","Town In Bulgaria");
insert into words (word,description) values ("yablanitsa","Town In Bulgaria");
insert into words (word,description) values ("kableshkovo","Town In Bulgaria");
insert into words (word,description) values ("opaka","Town In Bulgaria");
insert into words (word,description) values ("rila","Town In Bulgaria");
insert into words (word,description) values ("ugarchin","Town In Bulgaria");
insert into words (word,description) values ("dunavtsi","Town In Bulgaria");
insert into words (word,description) values ("dobrinishte","Town In Bulgaria");
insert into words (word,description) values ("hadzhidimovo","Town In Bulgaria");
insert into words (word,description) values ("bregovo","Town In Bulgaria");
insert into words (word,description) values ("byala cherkva","Town In Bulgaria");
insert into words (word,description) values ("zlataritsa","Town In Bulgaria");
insert into words (word,description) values ("kocherinovo","Town In Bulgaria");
insert into words (word,description) values ("dospat","Town In Bulgaria");
insert into words (word,description) values ("tran","Town In Bulgaria");
insert into words (word,description) values ("sadovo","Town In Bulgaria");
insert into words (word,description) values ("laki","Town In Bulgaria");
insert into words (word,description) values ("koprivshtitsa","Town In Bulgaria");
insert into words (word,description) values ("malko tarnovo","Town In Bulgaria");
insert into words (word,description) values ("loznitsa","Town In Bulgaria");
insert into words (word,description) values ("obzor","Town In Bulgaria");
insert into words (word,description) values ("kilifarevo","Town In Bulgaria");
insert into words (word,description) values ("borovo","Town In Bulgaria");
insert into words (word,description) values ("batanovtsi","Town In Bulgaria");
insert into words (word,description) values ("chernomorets","Town In Bulgaria");
insert into words (word,description) values ("aheloy","Town In Bulgaria");
insert into words (word,description) values ("byala","Town In Bulgaria");
insert into words (word,description) values ("pordim","Town In Bulgaria");
insert into words (word,description) values ("suhindol","Town In Bulgaria");
insert into words (word,description) values ("merichleri","Town In Bulgaria");
insert into words (word,description) values ("glavinitsa","Town In Bulgaria");
insert into words (word,description) values ("chiprovtsi","Town In Bulgaria");
insert into words (word,description) values ("kermen","Town In Bulgaria");
insert into words (word,description) values ("brezovo","Town In Bulgaria");
insert into words (word,description) values ("plachkovtsi","Town In Bulgaria");
insert into words (word,description) values ("zemen","Town In Bulgaria");
insert into words (word,description) values ("balgarovo","Town In Bulgaria");
insert into words (word,description) values ("alfatar","Town In Bulgaria");
insert into words (word,description) values ("boychinovtsi","Town In Bulgaria");
insert into words (word,description) values ("gramada","Town In Bulgaria");
insert into words (word,description) values ("senovo","Town In Bulgaria");
insert into words (word,description) values ("momin prohod","Town In Bulgaria");
insert into words (word,description) values ("kaolinovo","Town In Bulgaria");
insert into words (word,description) values ("shipka","Town In Bulgaria");
insert into words (word,description) values ("antonovo","Town In Bulgaria");
insert into words (word,description) values ("ahtopol","Town In Bulgaria");
insert into words (word,description) values ("boboshevo","Town In Bulgaria");
insert into words (word,description) values ("bolyarovo","Town In Bulgaria");
insert into words (word,description) values ("brusartsi","Town In Bulgaria");
insert into words (word,description) values ("klisura","Town In Bulgaria");
insert into words (word,description) values ("dimovo","Town In Bulgaria");
insert into words (word,description) values ("kiten","Town In Bulgaria");
insert into words (word,description) values ("pliska","Town In Bulgaria");
insert into words (word,description) values ("madzharovo","Town In Bulgaria");
insert into words (word,description) values ("melnik","Town In Bulgaria");
insert into words (word,description) values ("afghanistan","Country");
insert into words (word,description) values ("albania","Country");
insert into words (word,description) values ("algeria","Country");
insert into words (word,description) values ("andorra","Country");
insert into words (word,description) values ("angola","Country");
insert into words (word,description) values ("antigua and barbuda","Country");
insert into words (word,description) values ("argentina","Country");
insert into words (word,description) values ("armenia","Country");
insert into words (word,description) values ("australia","Country");
insert into words (word,description) values ("austria","Country");
insert into words (word,description) values ("azerbaijan","Country");
insert into words (word,description) values ("the bahamas","Country");
insert into words (word,description) values ("bahrain","Country");
insert into words (word,description) values ("bangladesh","Country");
insert into words (word,description) values ("barbados","Country");
insert into words (word,description) values ("belarus","Country");
insert into words (word,description) values ("belgium","Country");
insert into words (word,description) values ("belize","Country");
insert into words (word,description) values ("benin","Country");
insert into words (word,description) values ("bhutan","Country");
insert into words (word,description) values ("bolivia","Country");
insert into words (word,description) values ("bosnia and herzegovina","Country");
insert into words (word,description) values ("botswana","Country");
insert into words (word,description) values ("brazil","Country");
insert into words (word,description) values ("brunei","Country");
insert into words (word,description) values ("bulgaria","Country");
insert into words (word,description) values ("burkina faso","Country");
insert into words (word,description) values ("burundi","Country");
insert into words (word,description) values ("cabo verde","Country");
insert into words (word,description) values ("cambodia","Country");
insert into words (word,description) values ("cameroon","Country");
insert into words (word,description) values ("canada","Country");
insert into words (word,description) values ("central african republic","Country");
insert into words (word,description) values ("chad","Country");
insert into words (word,description) values ("chile","Country");
insert into words (word,description) values ("china","Country");
insert into words (word,description) values ("colombia","Country");
insert into words (word,description) values ("comoros","Country");
insert into words (word,description) values ("congo","Country");
insert into words (word,description) values ("costa rica","Country");
insert into words (word,description) values ("côte d’ivoire","Country");
insert into words (word,description) values ("croatia","Country");
insert into words (word,description) values ("cuba","Country");
insert into words (word,description) values ("cyprus","Country");
insert into words (word,description) values ("czech republic","Country");
insert into words (word,description) values ("denmark","Country");
insert into words (word,description) values ("djibouti","Country");
insert into words (word,description) values ("dominica","Country");
insert into words (word,description) values ("dominican republic","Country");
insert into words (word,description) values ("east timor","Country");
insert into words (word,description) values ("ecuador","Country");
insert into words (word,description) values ("egypt","Country");
insert into words (word,description) values ("el salvador","Country");
insert into words (word,description) values ("equatorial guinea","Country");
insert into words (word,description) values ("eritrea","Country");
insert into words (word,description) values ("estonia","Country");
insert into words (word,description) values ("ethiopia","Country");
insert into words (word,description) values ("fiji","Country");
insert into words (word,description) values ("finland","Country");
insert into words (word,description) values ("france","Country");
insert into words (word,description) values ("gabon","Country");
insert into words (word,description) values ("the gambia","Country");
insert into words (word,description) values ("georgia","Country");
insert into words (word,description) values ("germany","Country");
insert into words (word,description) values ("ghana","Country");
insert into words (word,description) values ("greece","Country");
insert into words (word,description) values ("grenada","Country");
insert into words (word,description) values ("guatemala","Country");
insert into words (word,description) values ("guinea","Country");
insert into words (word,description) values ("guinea-bissau","Country");
insert into words (word,description) values ("guyana","Country");
insert into words (word,description) values ("haiti","Country");
insert into words (word,description) values ("honduras","Country");
insert into words (word,description) values ("hungary","Country");
insert into words (word,description) values ("iceland","Country");
insert into words (word,description) values ("india","Country");
insert into words (word,description) values ("indonesia","Country");
insert into words (word,description) values ("iran","Country");
insert into words (word,description) values ("iraq","Country");
insert into words (word,description) values ("ireland","Country");
insert into words (word,description) values ("israel","Country");
insert into words (word,description) values ("italy","Country");
insert into words (word,description) values ("jamaica","Country");
insert into words (word,description) values ("japan","Country");
insert into words (word,description) values ("jordan","Country");
insert into words (word,description) values ("kazakhstan","Country");
insert into words (word,description) values ("kenya","Country");
insert into words (word,description) values ("kiribati","Country");
insert into words (word,description) values ("north korea","Country");
insert into words (word,description) values ("south korea","Country");
insert into words (word,description) values ("kosovo","Country");
insert into words (word,description) values ("kuwait","Country");
insert into words (word,description) values ("kyrgyzstan","Country");
insert into words (word,description) values ("laos","Country");
insert into words (word,description) values ("latvia","Country");
insert into words (word,description) values ("lebanon","Country");
insert into words (word,description) values ("lesotho","Country");
insert into words (word,description) values ("liberia","Country");
insert into words (word,description) values ("libya","Country");
insert into words (word,description) values ("liechtenstein","Country");
insert into words (word,description) values ("lithuania","Country");
insert into words (word,description) values ("luxembourg","Country");
insert into words (word,description) values ("macedonia","Country");
insert into words (word,description) values ("madagascar","Country");
insert into words (word,description) values ("malawi","Country");
insert into words (word,description) values ("malaysia","Country");
insert into words (word,description) values ("maldives","Country");
insert into words (word,description) values ("mali","Country");
insert into words (word,description) values ("malta","Country");
insert into words (word,description) values ("marshall islands","Country");
insert into words (word,description) values ("mauritania","Country");
insert into words (word,description) values ("mauritius","Country");
insert into words (word,description) values ("mexico","Country");
insert into words (word,description) values ("micronesia","Country");
insert into words (word,description) values ("moldova","Country");
insert into words (word,description) values ("monaco","Country");
insert into words (word,description) values ("mongolia","Country");
insert into words (word,description) values ("montenegro","Country");
insert into words (word,description) values ("morocco","Country");
insert into words (word,description) values ("mozambique","Country");
insert into words (word,description) values ("myanmar","Country");
insert into words (word,description) values ("namibia","Country");
insert into words (word,description) values ("nauru","Country");
insert into words (word,description) values ("nepal","Country");
insert into words (word,description) values ("netherlands","Country");
insert into words (word,description) values ("new zealand","Country");
insert into words (word,description) values ("nicaragua","Country");
insert into words (word,description) values ("niger","Country");
insert into words (word,description) values ("nigeria","Country");
insert into words (word,description) values ("norway","Country");
insert into words (word,description) values ("oman","Country");
insert into words (word,description) values ("pakistan","Country");
insert into words (word,description) values ("palau","Country");
insert into words (word,description) values ("panama","Country");
insert into words (word,description) values ("papua new guinea","Country");
insert into words (word,description) values ("paraguay","Country");
insert into words (word,description) values ("peru","Country");
insert into words (word,description) values ("philippines","Country");
insert into words (word,description) values ("poland","Country");
insert into words (word,description) values ("portugal","Country");
insert into words (word,description) values ("qatar","Country");
insert into words (word,description) values ("romania","Country");
insert into words (word,description) values ("russia","Country");
insert into words (word,description) values ("rwanda","Country");
insert into words (word,description) values ("saint kitts and nevis","Country");
insert into words (word,description) values ("saint lucia","Country");
insert into words (word,description) values ("saint vincent and the grenadines","Country");
insert into words (word,description) values ("samoa","Country");
insert into words (word,description) values ("san marino","Country");
insert into words (word,description) values ("sao tome and principe","Country");
insert into words (word,description) values ("saudi arabia","Country");
insert into words (word,description) values ("senegal","Country");
insert into words (word,description) values ("serbia","Country");
insert into words (word,description) values ("seychelles","Country");
insert into words (word,description) values ("sierra leone","Country");
insert into words (word,description) values ("singapore","Country");
insert into words (word,description) values ("slovakia","Country");
insert into words (word,description) values ("slovenia","Country");
insert into words (word,description) values ("solomon islands","Country");
insert into words (word,description) values ("somalia","Country");
insert into words (word,description) values ("south africa","Country");
insert into words (word,description) values ("spain","Country");
insert into words (word,description) values ("sri lanka","Country");
insert into words (word,description) values ("sudan","Country");
insert into words (word,description) values ("south sudan","Country");
insert into words (word,description) values ("suriname","Country");
insert into words (word,description) values ("swaziland","Country");
insert into words (word,description) values ("sweden","Country");
insert into words (word,description) values ("switzerland","Country");
insert into words (word,description) values ("syria","Country");
insert into words (word,description) values ("taiwan","Country");
insert into words (word,description) values ("tajikistan","Country");
insert into words (word,description) values ("tanzania","Country");
insert into words (word,description) values ("thailand","Country");
insert into words (word,description) values ("togo","Country");
insert into words (word,description) values ("tonga","Country");
insert into words (word,description) values ("trinidad and tobago","Country");
insert into words (word,description) values ("tunisia","Country");
insert into words (word,description) values ("turkey","Country");
insert into words (word,description) values ("turkmenistan","Country");
insert into words (word,description) values ("tuvalu","Country");
insert into words (word,description) values ("uganda","Country");
insert into words (word,description) values ("ukraine","Country");
insert into words (word,description) values ("united arab emirates","Country");
insert into words (word,description) values ("united kingdom","Country");
insert into words (word,description) values ("united states","Country");
insert into words (word,description) values ("uruguay","Country");
insert into words (word,description) values ("uzbekistan","Country");
insert into words (word,description) values ("vanuatu","Country");
insert into words (word,description) values ("vatican city","Country");
insert into words (word,description) values ("venezuela","Country");
insert into words (word,description) values ("vietnam","Country");
insert into words (word,description) values ("yemen","Country");
insert into words (word,description) values ("zambia","Country");
insert into words (word,description) values ("zimbabwe","Country");
insert into words (word,description) values ("alabama","US State");
insert into words (word,description) values ("alaska","US State");
insert into words (word,description) values ("arizona","US State");
insert into words (word,description) values ("arkansas","US State");
insert into words (word,description) values ("california","US State");
insert into words (word,description) values ("colorado","US State");
insert into words (word,description) values ("connecticut","US State");
insert into words (word,description) values ("delaware","US State");
insert into words (word,description) values ("florida","US State");
insert into words (word,description) values ("georgia","US State");
insert into words (word,description) values ("hawaii","US State");
insert into words (word,description) values ("idaho","US State");
insert into words (word,description) values ("illinois","US State");
insert into words (word,description) values ("indiana","US State");
insert into words (word,description) values ("iowa","US State");
insert into words (word,description) values ("kansas","US State");
insert into words (word,description) values ("kentucky","US State");
insert into words (word,description) values ("louisiana","US State");
insert into words (word,description) values ("maine","US State");
insert into words (word,description) values ("maryland","US State");
insert into words (word,description) values ("massachusetts","US State");
insert into words (word,description) values ("michigan","US State");
insert into words (word,description) values ("minnesota","US State");
insert into words (word,description) values ("mississippi","US State");
insert into words (word,description) values ("missouri","US State");
insert into words (word,description) values ("montana","US State");
insert into words (word,description) values ("nebraska","US State");
insert into words (word,description) values ("nevada","US State");
insert into words (word,description) values ("new hampshire","US State");
insert into words (word,description) values ("new jersey","US State");
insert into words (word,description) values ("new mexico","US State");
insert into words (word,description) values ("new york","US State");
insert into words (word,description) values ("namibia","US State");
insert into words (word,description) values ("north dakota","US State");
insert into words (word,description) values ("ohio","US State");
insert into words (word,description) values ("oklahoma","US State");
insert into words (word,description) values ("oregon","US State");
insert into words (word,description) values ("pennsylvania","US State");
insert into words (word,description) values ("rhode island","US State");
insert into words (word,description) values ("south carolina","US State");
insert into words (word,description) values ("south dakota","US State");
insert into words (word,description) values ("tennessee","US State");
insert into words (word,description) values ("texas","US State");
insert into words (word,description) values ("utah","US State");
insert into words (word,description) values ("vermont","US State");
insert into words (word,description) values ("virginia","US State");
insert into words (word,description) values ("washington","US State");
insert into words (word,description) values ("west virginia","US State");
insert into words (word,description) values ("wisconsin","US State");
insert into words (word,description) values ("wyoming","US State");
