insert into words (word,description,keyboard) values ("софия","Град в България","cyr");
insert into words (word,description,keyboard) values ("пловдив","Град в България","cyr");
insert into words (word,description,keyboard) values ("варна","Град в България","cyr");
insert into words (word,description,keyboard) values ("бургас","Град в България","cyr");
insert into words (word,description,keyboard) values ("русе","Град в България","cyr");
insert into words (word,description,keyboard) values ("стара загора","Град в България","cyr");
insert into words (word,description,keyboard) values ("плевен","Град в България","cyr");
insert into words (word,description,keyboard) values ("добрич","Град в България","cyr");
insert into words (word,description,keyboard) values ("сливен","Град в България","cyr");
insert into words (word,description,keyboard) values ("шумен","Град в България","cyr");
insert into words (word,description,keyboard) values ("перник","Град в България","cyr");
insert into words (word,description,keyboard) values ("хасково","Град в България","cyr");
insert into words (word,description,keyboard) values ("ямбол","Град в България","cyr");
insert into words (word,description,keyboard) values ("пазарджик","Град в България","cyr");
insert into words (word,description,keyboard) values ("благоевград","Град в България","cyr");
insert into words (word,description,keyboard) values ("велико търново","Град в България","cyr");
insert into words (word,description,keyboard) values ("враца","Град в България","cyr");
insert into words (word,description,keyboard) values ("габрово","Град в България","cyr");
insert into words (word,description,keyboard) values ("асеновград","Град в България","cyr");
insert into words (word,description,keyboard) values ("видин","Град в България","cyr");
insert into words (word,description,keyboard) values ("казанлък","Град в България","cyr");
insert into words (word,description,keyboard) values ("кюстендил","Град в България","cyr");
insert into words (word,description,keyboard) values ("кърджали","Град в България","cyr");
insert into words (word,description,keyboard) values ("монтана","Град в България","cyr");
insert into words (word,description,keyboard) values ("димитровград","Град в България","cyr");
insert into words (word,description,keyboard) values ("тарговище","Град в България","cyr");
insert into words (word,description,keyboard) values ("ловеч","Град в България","cyr");
insert into words (word,description,keyboard) values ("силистра","Град в България","cyr");
insert into words (word,description,keyboard) values ("дупница","Град в България","cyr");
insert into words (word,description,keyboard) values ("свищов","Град в България","cyr");
insert into words (word,description,keyboard) values ("разград","Град в България","cyr");
insert into words (word,description,keyboard) values ("горна оряховица","Град в България","cyr");
insert into words (word,description,keyboard) values ("смолян","Град в България","cyr");
insert into words (word,description,keyboard) values ("петрич","Град в България","cyr");
insert into words (word,description,keyboard) values ("сандански","Град в България","cyr");
insert into words (word,description,keyboard) values ("самоков","Град в България","cyr");
insert into words (word,description,keyboard) values ("севлиево","Град в България","cyr");
insert into words (word,description,keyboard) values ("лом","Град в България","cyr");
insert into words (word,description,keyboard) values ("карлово","Град в България","cyr");
insert into words (word,description,keyboard) values ("велинград","Град в България","cyr");
insert into words (word,description,keyboard) values ("нова загора","Град в България","cyr");
insert into words (word,description,keyboard) values ("троян","Град в България","cyr");
insert into words (word,description,keyboard) values ("айтос","Град в България","cyr");
insert into words (word,description,keyboard) values ("ботевград","Град в България","cyr");
insert into words (word,description,keyboard) values ("гоце делчев","Град в България","cyr");
insert into words (word,description,keyboard) values ("пещера","Град в България","cyr");
insert into words (word,description,keyboard) values ("харманли","Град в България","cyr");
insert into words (word,description,keyboard) values ("карнобат","Град в България","cyr");
insert into words (word,description,keyboard) values ("свиленград","Град в България","cyr");
insert into words (word,description,keyboard) values ("панагюрище","Град в България","cyr");
insert into words (word,description,keyboard) values ("чирпан","Град в България","cyr");
insert into words (word,description,keyboard) values ("попово","Град в България","cyr");
insert into words (word,description,keyboard) values ("раковски","Град в България","cyr");
insert into words (word,description,keyboard) values ("радомир","Град в България","cyr");
insert into words (word,description,keyboard) values ("нови искър","Град в България","cyr");
insert into words (word,description,keyboard) values ("козлодуй","Град в България","cyr");
insert into words (word,description,keyboard) values ("първомай","Град в България","cyr");
insert into words (word,description,keyboard) values ("берковица","Град в България","cyr");
insert into words (word,description,keyboard) values ("червен бряг","Град в България","cyr");
insert into words (word,description,keyboard) values ("поморие","Град в България","cyr");
insert into words (word,description,keyboard) values ("ихтиман","Град в България","cyr");
insert into words (word,description,keyboard) values ("раднево","Град в България","cyr");
insert into words (word,description,keyboard) values ("провадия","Град в България","cyr");
insert into words (word,description,keyboard) values ("нови пазар","Град в България","cyr");
insert into words (word,description,keyboard) values ("разлог","Град в България","cyr");
insert into words (word,description,keyboard) values ("бяла слатина","Град в България","cyr");
insert into words (word,description,keyboard) values ("несебър","Град в България","cyr");
insert into words (word,description,keyboard) values ("балчик","Град в България","cyr");
insert into words (word,description,keyboard) values ("костинброд","Град в България","cyr");
insert into words (word,description,keyboard) values ("стамболийски","Град в България","cyr");
insert into words (word,description,keyboard) values ("каварна","Град в България","cyr");
insert into words (word,description,keyboard) values ("кнежа","Град в България","cyr");
insert into words (word,description,keyboard) values ("павликени","Град в България","cyr");
insert into words (word,description,keyboard) values ("мездра","Град в България","cyr");
insert into words (word,description,keyboard) values ("етрополе","Град в България","cyr");
insert into words (word,description,keyboard) values ("левски","Град в България","cyr");
insert into words (word,description,keyboard) values ("тетевен","Град в България","cyr");
insert into words (word,description,keyboard) values ("елхово","Град в България","cyr");
insert into words (word,description,keyboard) values ("банкя","Град в България","cyr");
insert into words (word,description,keyboard) values ("трявна","Град в България","cyr");
insert into words (word,description,keyboard) values ("луковит","Град в България","cyr");
insert into words (word,description,keyboard) values ("тутракан","Град в България","cyr");
insert into words (word,description,keyboard) values ("средец","Град в България","cyr");
insert into words (word,description,keyboard) values ("сопот","Град в България","cyr");
insert into words (word,description,keyboard) values ("бяла","Град в България","cyr");
insert into words (word,description,keyboard) values ("велики преслав","Град в България","cyr");
insert into words (word,description,keyboard) values ("исперих","Град в България","cyr");
insert into words (word,description,keyboard) values ("белене","Град в България","cyr");
insert into words (word,description,keyboard) values ("омуртаг","Град в България","cyr");
insert into words (word,description,keyboard) values ("банско","Град в България","cyr");
insert into words (word,description,keyboard) values ("кричим","Град в България","cyr");
insert into words (word,description,keyboard) values ("гълъбово","Град в България","cyr");
insert into words (word,description,keyboard) values ("девня","Град в България","cyr");
insert into words (word,description,keyboard) values ("септември","Град в България","cyr");
insert into words (word,description,keyboard) values ("ракитово","Град в България","cyr");
insert into words (word,description,keyboard) values ("лясковец","Град в България","cyr");
insert into words (word,description,keyboard) values ("своге","Град в България","cyr");
insert into words (word,description,keyboard) values ("аксаково","Град в България","cyr");
insert into words (word,description,keyboard) values ("кубрат","Град в България","cyr");
insert into words (word,description,keyboard) values ("дряново","Град в България","cyr");
insert into words (word,description,keyboard) values ("белослав","Град в България","cyr");
insert into words (word,description,keyboard) values ("пирдоп","Град в България","cyr");
insert into words (word,description,keyboard) values ("любимец","Град в България","cyr");
insert into words (word,description,keyboard) values ("момчилград","Град в България","cyr");
insert into words (word,description,keyboard) values ("сливница","Град в България","cyr");
insert into words (word,description,keyboard) values ("хисаря","Град в България","cyr");
insert into words (word,description,keyboard) values ("златоград","Град в България","cyr");
insert into words (word,description,keyboard) values ("костенец","Град в България","cyr");
insert into words (word,description,keyboard) values ("девин","Град в България","cyr");
insert into words (word,description,keyboard) values ("генерал тошево","Град в България","cyr");
insert into words (word,description,keyboard) values ("симеоновград","Град в България","cyr");
insert into words (word,description,keyboard) values ("симитли","Град в България","cyr");
insert into words (word,description,keyboard) values ("елин пелин","Град в България","cyr");
insert into words (word,description,keyboard) values ("долни чифлик","Град в България","cyr");
insert into words (word,description,keyboard) values ("тервел","Град в България","cyr");
insert into words (word,description,keyboard) values ("дулово","Град в България","cyr");
insert into words (word,description,keyboard) values ("вършец","Град в България","cyr");
insert into words (word,description,keyboard) values ("котел","Град в България","cyr");
insert into words (word,description,keyboard) values ("мадан","Град в България","cyr");
insert into words (word,description,keyboard) values ("стралджа","Град в България","cyr");
insert into words (word,description,keyboard) values ("съединение","Град в България","cyr");
insert into words (word,description,keyboard) values ("бобов дол","Град в България","cyr");
insert into words (word,description,keyboard) values ("царево","Град в България","cyr");
insert into words (word,description,keyboard) values ("куклен","Град в България","cyr");
insert into words (word,description,keyboard) values ("твърдица","Град в България","cyr");
insert into words (word,description,keyboard) values ("якоруда","Град в България","cyr");
insert into words (word,description,keyboard) values ("елена","Град в България","cyr");
insert into words (word,description,keyboard) values ("тополовград","Град в България","cyr");
insert into words (word,description,keyboard) values ("божурище","Град в България","cyr");
insert into words (word,description,keyboard) values ("чепеларе","Град в България","cyr");
insert into words (word,description,keyboard) values ("оряхово","Град в България","cyr");
insert into words (word,description,keyboard) values ("созопол","Град в България","cyr");
insert into words (word,description,keyboard) values ("белоградчик","Град в България","cyr");
insert into words (word,description,keyboard) values ("перущица","Град в България","cyr");
insert into words (word,description,keyboard) values ("златица","Град в България","cyr");
insert into words (word,description,keyboard) values ("стражица","Град в България","cyr");
insert into words (word,description,keyboard) values ("крумовград","Град в България","cyr");
insert into words (word,description,keyboard) values ("камено","Град в България","cyr");
insert into words (word,description,keyboard) values ("дългопол","Град в България","cyr");
insert into words (word,description,keyboard) values ("ветово","Град в България","cyr");
insert into words (word,description,keyboard) values ("суворово","Град в България","cyr");
insert into words (word,description,keyboard) values ("долни дъбник","Град в България","cyr");
insert into words (word,description,keyboard) values ("долна баня","Град в България","cyr");
insert into words (word,description,keyboard) values ("правец","Град в България","cyr");
insert into words (word,description,keyboard) values ("неделино","Град в България","cyr");
insert into words (word,description,keyboard) values ("полски тръмбеш","Град в България","cyr");
insert into words (word,description,keyboard) values ("тръстеник","Град в България","cyr");
insert into words (word,description,keyboard) values ("брацигово","Град в България","cyr");
insert into words (word,description,keyboard) values ("койнаре","Град в България","cyr");
insert into words (word,description,keyboard) values ("годеч","Град в България","cyr");
insert into words (word,description,keyboard) values ("славяново","Град в България","cyr");
insert into words (word,description,keyboard) values ("две могили","Град в България","cyr");
insert into words (word,description,keyboard) values ("костандово","Град в България","cyr");
insert into words (word,description,keyboard) values ("дебелец","Град в България","cyr");
insert into words (word,description,keyboard) values ("стрелча","Град в България","cyr");
insert into words (word,description,keyboard) values ("сапарева баня","Град в България","cyr");
insert into words (word,description,keyboard) values ("игнатиево","Град в България","cyr");
insert into words (word,description,keyboard) values ("смядово","Град в България","cyr");
insert into words (word,description,keyboard) values ("брезник","Град в България","cyr");
insert into words (word,description,keyboard) values ("свети влас","Град в България","cyr");
insert into words (word,description,keyboard) values ("никопол","Град в България","cyr");
insert into words (word,description,keyboard) values ("шивачево","Град в България","cyr");
insert into words (word,description,keyboard) values ("белово","Град в България","cyr");
insert into words (word,description,keyboard) values ("цар калоян","Град в България","cyr");
insert into words (word,description,keyboard) values ("ивайловград","Град в България","cyr");
insert into words (word,description,keyboard) values ("вълчедръм","Град в България","cyr");
insert into words (word,description,keyboard) values ("мартен","Град в България","cyr");
insert into words (word,description,keyboard) values ("глоджево","Град в България","cyr");
insert into words (word,description,keyboard) values ("сърница","Град в България","cyr");
insert into words (word,description,keyboard) values ("летница","Град в България","cyr");
insert into words (word,description,keyboard) values ("върбица","Град в България","cyr");
insert into words (word,description,keyboard) values ("искър","Град в България","cyr");
insert into words (word,description,keyboard) values ("ардино","Град в България","cyr");
insert into words (word,description,keyboard) values ("шабла","Град в България","cyr");
insert into words (word,description,keyboard) values ("рудозем","Град в България","cyr");
insert into words (word,description,keyboard) values ("ветрен","Град в България","cyr");
insert into words (word,description,keyboard) values ("кресна","Град в България","cyr");
insert into words (word,description,keyboard) values ("баня","Град в България","cyr");
insert into words (word,description,keyboard) values ("батак","Град в България","cyr");
insert into words (word,description,keyboard) values ("мъглиж","Град в България","cyr");
insert into words (word,description,keyboard) values ("вълчи дол","Град в България","cyr");
insert into words (word,description,keyboard) values ("гулянци","Град в България","cyr");
insert into words (word,description,keyboard) values ("драгоман","Град в България","cyr");
insert into words (word,description,keyboard) values ("завет","Град в България","cyr");
insert into words (word,description,keyboard) values ("крън","Град в България","cyr");
insert into words (word,description,keyboard) values ("мизия","Град в България","cyr");
insert into words (word,description,keyboard) values ("приморско","Град в България","cyr");
insert into words (word,description,keyboard) values ("сунгурларе","Град в България","cyr");
insert into words (word,description,keyboard) values ("долна митрополия","Град в България","cyr");
insert into words (word,description,keyboard) values ("криводол","Град в България","cyr");
insert into words (word,description,keyboard) values ("кула","Град в България","cyr");
insert into words (word,description,keyboard) values ("калофер","Град в България","cyr");
insert into words (word,description,keyboard) values ("сливо поле","Град в България","cyr");
insert into words (word,description,keyboard) values ("каспичан","Град в България","cyr");
insert into words (word,description,keyboard) values ("априлци","Град в България","cyr");
insert into words (word,description,keyboard) values ("белица","Град в България","cyr");
insert into words (word,description,keyboard) values ("роман","Град в България","cyr");
insert into words (word,description,keyboard) values ("джебел","Град в България","cyr");
insert into words (word,description,keyboard) values ("долна оряховица","Град в България","cyr");
insert into words (word,description,keyboard) values ("бухово","Град в България","cyr");
insert into words (word,description,keyboard) values ("гурково","Град в България","cyr");
insert into words (word,description,keyboard) values ("павел баня","Град в България","cyr");
insert into words (word,description,keyboard) values ("николаево","Град в България","cyr");
insert into words (word,description,keyboard) values ("ябланица","Град в България","cyr");
insert into words (word,description,keyboard) values ("каблешково","Град в България","cyr");
insert into words (word,description,keyboard) values ("опака","Град в България","cyr");
insert into words (word,description,keyboard) values ("рила","Град в България","cyr");
insert into words (word,description,keyboard) values ("угърчин","Град в България","cyr");
insert into words (word,description,keyboard) values ("дунавци","Град в България","cyr");
insert into words (word,description,keyboard) values ("добринище","Град в България","cyr");
insert into words (word,description,keyboard) values ("хаджидимово","Град в България","cyr");
insert into words (word,description,keyboard) values ("брегово","Град в България","cyr");
insert into words (word,description,keyboard) values ("бяла черква","Град в България","cyr");
insert into words (word,description,keyboard) values ("златарица","Град в България","cyr");
insert into words (word,description,keyboard) values ("кочериново","Град в България","cyr");
insert into words (word,description,keyboard) values ("доспат","Град в България","cyr");
insert into words (word,description,keyboard) values ("трън","Град в България","cyr");
insert into words (word,description,keyboard) values ("садово","Град в България","cyr");
insert into words (word,description,keyboard) values ("лъки","Град в България","cyr");
insert into words (word,description,keyboard) values ("копривщица","Град в България","cyr");
insert into words (word,description,keyboard) values ("малко търново","Град в България","cyr");
insert into words (word,description,keyboard) values ("лозница","Град в България","cyr");
insert into words (word,description,keyboard) values ("обзор","Град в България","cyr");
insert into words (word,description,keyboard) values ("килифарево","Град в България","cyr");
insert into words (word,description,keyboard) values ("борово","Град в България","cyr");
insert into words (word,description,keyboard) values ("батановци","Град в България","cyr");
insert into words (word,description,keyboard) values ("черноморец","Град в България","cyr");
insert into words (word,description,keyboard) values ("ахелой","Град в България","cyr");
insert into words (word,description,keyboard) values ("бяла","Град в България","cyr");
insert into words (word,description,keyboard) values ("пордим","Град в България","cyr");
insert into words (word,description,keyboard) values ("сухиндол","Град в България","cyr");
insert into words (word,description,keyboard) values ("меричлери","Град в България","cyr");
insert into words (word,description,keyboard) values ("главиница","Град в България","cyr");
insert into words (word,description,keyboard) values ("чипровци","Град в България","cyr");
insert into words (word,description,keyboard) values ("кермен","Град в България","cyr");
insert into words (word,description,keyboard) values ("брезово","Град в България","cyr");
insert into words (word,description,keyboard) values ("плачковци","Град в България","cyr");
insert into words (word,description,keyboard) values ("земен","Град в България","cyr");
insert into words (word,description,keyboard) values ("българово","Град в България","cyr");
insert into words (word,description,keyboard) values ("алфатар","Град в България","cyr");
insert into words (word,description,keyboard) values ("бойчиновци","Град в България","cyr");
insert into words (word,description,keyboard) values ("грамада","Град в България","cyr");
insert into words (word,description,keyboard) values ("сеново","Град в България","cyr");
insert into words (word,description,keyboard) values ("момин проход","Град в България","cyr");
insert into words (word,description,keyboard) values ("каолиново","Град в България","cyr");
insert into words (word,description,keyboard) values ("шипка","Град в България","cyr");
insert into words (word,description,keyboard) values ("антоново","Град в България","cyr");
insert into words (word,description,keyboard) values ("ахтопол","Град в България","cyr");
insert into words (word,description,keyboard) values ("бобошево","Град в България","cyr");
insert into words (word,description,keyboard) values ("болярово","Град в България","cyr");
insert into words (word,description,keyboard) values ("брусарци","Град в България","cyr");
insert into words (word,description,keyboard) values ("клисура","Град в България","cyr");
insert into words (word,description,keyboard) values ("димово","Град в България","cyr");
insert into words (word,description,keyboard) values ("китен","Град в България","cyr");
insert into words (word,description,keyboard) values ("плиска","Град в България","cyr");
insert into words (word,description,keyboard) values ("маджарово","Град в България","cyr");
insert into words (word,description,keyboard) values ("мелник","Град в България","cyr");
insert into words (word,description,keyboard) values ("afghanistan","Country","latin");
insert into words (word,description,keyboard) values ("albania","Country","latin");
insert into words (word,description,keyboard) values ("algeria","Country","latin");
insert into words (word,description,keyboard) values ("andorra","Country","latin");
insert into words (word,description,keyboard) values ("angola","Country","latin");
insert into words (word,description,keyboard) values ("antigua and barbuda","Country","latin");
insert into words (word,description,keyboard) values ("argentina","Country","latin");
insert into words (word,description,keyboard) values ("armenia","Country","latin");
insert into words (word,description,keyboard) values ("australia","Country","latin");
insert into words (word,description,keyboard) values ("austria","Country","latin");
insert into words (word,description,keyboard) values ("azerbaijan","Country","latin");
insert into words (word,description,keyboard) values ("the bahamas","Country","latin");
insert into words (word,description,keyboard) values ("bahrain","Country","latin");
insert into words (word,description,keyboard) values ("bangladesh","Country","latin");
insert into words (word,description,keyboard) values ("barbados","Country","latin");
insert into words (word,description,keyboard) values ("belarus","Country","latin");
insert into words (word,description,keyboard) values ("belgium","Country","latin");
insert into words (word,description,keyboard) values ("belize","Country","latin");
insert into words (word,description,keyboard) values ("benin","Country","latin");
insert into words (word,description,keyboard) values ("bhutan","Country","latin");
insert into words (word,description,keyboard) values ("bolivia","Country","latin");
insert into words (word,description,keyboard) values ("bosnia and herzegovina","Country","latin");
insert into words (word,description,keyboard) values ("botswana","Country","latin");
insert into words (word,description,keyboard) values ("brazil","Country","latin");
insert into words (word,description,keyboard) values ("brunei","Country","latin");
insert into words (word,description,keyboard) values ("bulgaria","Country","latin");
insert into words (word,description,keyboard) values ("burkina faso","Country","latin");
insert into words (word,description,keyboard) values ("burundi","Country","latin");
insert into words (word,description,keyboard) values ("cabo verde","Country","latin");
insert into words (word,description,keyboard) values ("cambodia","Country","latin");
insert into words (word,description,keyboard) values ("cameroon","Country","latin");
insert into words (word,description,keyboard) values ("canada","Country","latin");
insert into words (word,description,keyboard) values ("central african republic","Country","latin");
insert into words (word,description,keyboard) values ("chad","Country","latin");
insert into words (word,description,keyboard) values ("chile","Country","latin");
insert into words (word,description,keyboard) values ("china","Country","latin");
insert into words (word,description,keyboard) values ("colombia","Country","latin");
insert into words (word,description,keyboard) values ("comoros","Country","latin");
insert into words (word,description,keyboard) values ("congo","Country","latin");
insert into words (word,description,keyboard) values ("costa rica","Country","latin");
insert into words (word,description,keyboard) values ("côte d’ivoire","Country","latin");
insert into words (word,description,keyboard) values ("croatia","Country","latin");
insert into words (word,description,keyboard) values ("cuba","Country","latin");
insert into words (word,description,keyboard) values ("cyprus","Country","latin");
insert into words (word,description,keyboard) values ("czech republic","Country","latin");
insert into words (word,description,keyboard) values ("denmark","Country","latin");
insert into words (word,description,keyboard) values ("djibouti","Country","latin");
insert into words (word,description,keyboard) values ("dominica","Country","latin");
insert into words (word,description,keyboard) values ("dominican republic","Country","latin");
insert into words (word,description,keyboard) values ("east timor","Country","latin");
insert into words (word,description,keyboard) values ("ecuador","Country","latin");
insert into words (word,description,keyboard) values ("egypt","Country","latin");
insert into words (word,description,keyboard) values ("el salvador","Country","latin");
insert into words (word,description,keyboard) values ("equatorial guinea","Country","latin");
insert into words (word,description,keyboard) values ("eritrea","Country","latin");
insert into words (word,description,keyboard) values ("estonia","Country","latin");
insert into words (word,description,keyboard) values ("ethiopia","Country","latin");
insert into words (word,description,keyboard) values ("fiji","Country","latin");
insert into words (word,description,keyboard) values ("finland","Country","latin");
insert into words (word,description,keyboard) values ("france","Country","latin");
insert into words (word,description,keyboard) values ("gabon","Country","latin");
insert into words (word,description,keyboard) values ("the gambia","Country","latin");
insert into words (word,description,keyboard) values ("georgia","Country","latin");
insert into words (word,description,keyboard) values ("germany","Country","latin");
insert into words (word,description,keyboard) values ("ghana","Country","latin");
insert into words (word,description,keyboard) values ("greece","Country","latin");
insert into words (word,description,keyboard) values ("grenada","Country","latin");
insert into words (word,description,keyboard) values ("guatemala","Country","latin");
insert into words (word,description,keyboard) values ("guinea","Country","latin");
insert into words (word,description,keyboard) values ("guinea-bissau","Country","latin");
insert into words (word,description,keyboard) values ("guyana","Country","latin");
insert into words (word,description,keyboard) values ("haiti","Country","latin");
insert into words (word,description,keyboard) values ("honduras","Country","latin");
insert into words (word,description,keyboard) values ("hungary","Country","latin");
insert into words (word,description,keyboard) values ("iceland","Country","latin");
insert into words (word,description,keyboard) values ("india","Country","latin");
insert into words (word,description,keyboard) values ("indonesia","Country","latin");
insert into words (word,description,keyboard) values ("iran","Country","latin");
insert into words (word,description,keyboard) values ("iraq","Country","latin");
insert into words (word,description,keyboard) values ("ireland","Country","latin");
insert into words (word,description,keyboard) values ("israel","Country","latin");
insert into words (word,description,keyboard) values ("italy","Country","latin");
insert into words (word,description,keyboard) values ("jamaica","Country","latin");
insert into words (word,description,keyboard) values ("japan","Country","latin");
insert into words (word,description,keyboard) values ("jordan","Country","latin");
insert into words (word,description,keyboard) values ("kazakhstan","Country","latin");
insert into words (word,description,keyboard) values ("kenya","Country","latin");
insert into words (word,description,keyboard) values ("kiribati","Country","latin");
insert into words (word,description,keyboard) values ("north korea","Country","latin");
insert into words (word,description,keyboard) values ("south korea","Country","latin");
insert into words (word,description,keyboard) values ("kosovo","Country","latin");
insert into words (word,description,keyboard) values ("kuwait","Country","latin");
insert into words (word,description,keyboard) values ("kyrgyzstan","Country","latin");
insert into words (word,description,keyboard) values ("laos","Country","latin");
insert into words (word,description,keyboard) values ("latvia","Country","latin");
insert into words (word,description,keyboard) values ("lebanon","Country","latin");
insert into words (word,description,keyboard) values ("lesotho","Country","latin");
insert into words (word,description,keyboard) values ("liberia","Country","latin");
insert into words (word,description,keyboard) values ("libya","Country","latin");
insert into words (word,description,keyboard) values ("liechtenstein","Country","latin");
insert into words (word,description,keyboard) values ("lithuania","Country","latin");
insert into words (word,description,keyboard) values ("luxembourg","Country","latin");
insert into words (word,description,keyboard) values ("macedonia","Country","latin");
insert into words (word,description,keyboard) values ("madagascar","Country","latin");
insert into words (word,description,keyboard) values ("malawi","Country","latin");
insert into words (word,description,keyboard) values ("malaysia","Country","latin");
insert into words (word,description,keyboard) values ("maldives","Country","latin");
insert into words (word,description,keyboard) values ("mali","Country","latin");
insert into words (word,description,keyboard) values ("malta","Country","latin");
insert into words (word,description,keyboard) values ("marshall islands","Country","latin");
insert into words (word,description,keyboard) values ("mauritania","Country","latin");
insert into words (word,description,keyboard) values ("mauritius","Country","latin");
insert into words (word,description,keyboard) values ("mexico","Country","latin");
insert into words (word,description,keyboard) values ("micronesia","Country","latin");
insert into words (word,description,keyboard) values ("moldova","Country","latin");
insert into words (word,description,keyboard) values ("monaco","Country","latin");
insert into words (word,description,keyboard) values ("mongolia","Country","latin");
insert into words (word,description,keyboard) values ("montenegro","Country","latin");
insert into words (word,description,keyboard) values ("morocco","Country","latin");
insert into words (word,description,keyboard) values ("mozambique","Country","latin");
insert into words (word,description,keyboard) values ("myanmar","Country","latin");
insert into words (word,description,keyboard) values ("namibia","Country","latin");
insert into words (word,description,keyboard) values ("nauru","Country","latin");
insert into words (word,description,keyboard) values ("nepal","Country","latin");
insert into words (word,description,keyboard) values ("netherlands","Country","latin");
insert into words (word,description,keyboard) values ("new zealand","Country","latin");
insert into words (word,description,keyboard) values ("nicaragua","Country","latin");
insert into words (word,description,keyboard) values ("niger","Country","latin");
insert into words (word,description,keyboard) values ("nigeria","Country","latin");
insert into words (word,description,keyboard) values ("norway","Country","latin");
insert into words (word,description,keyboard) values ("oman","Country","latin");
insert into words (word,description,keyboard) values ("pakistan","Country","latin");
insert into words (word,description,keyboard) values ("palau","Country","latin");
insert into words (word,description,keyboard) values ("panama","Country","latin");
insert into words (word,description,keyboard) values ("papua new guinea","Country","latin");
insert into words (word,description,keyboard) values ("paraguay","Country","latin");
insert into words (word,description,keyboard) values ("peru","Country","latin");
insert into words (word,description,keyboard) values ("philippines","Country","latin");
insert into words (word,description,keyboard) values ("poland","Country","latin");
insert into words (word,description,keyboard) values ("portugal","Country","latin");
insert into words (word,description,keyboard) values ("qatar","Country","latin");
insert into words (word,description,keyboard) values ("romania","Country","latin");
insert into words (word,description,keyboard) values ("russia","Country","latin");
insert into words (word,description,keyboard) values ("rwanda","Country","latin");
insert into words (word,description,keyboard) values ("saint kitts and nevis","Country","latin");
insert into words (word,description,keyboard) values ("saint lucia","Country","latin");
insert into words (word,description,keyboard) values ("saint vincent and the grenadines","Country","latin");
insert into words (word,description,keyboard) values ("samoa","Country","latin");
insert into words (word,description,keyboard) values ("san marino","Country","latin");
insert into words (word,description,keyboard) values ("sao tome and principe","Country","latin");
insert into words (word,description,keyboard) values ("saudi arabia","Country","latin");
insert into words (word,description,keyboard) values ("senegal","Country","latin");
insert into words (word,description,keyboard) values ("serbia","Country","latin");
insert into words (word,description,keyboard) values ("seychelles","Country","latin");
insert into words (word,description,keyboard) values ("sierra leone","Country","latin");
insert into words (word,description,keyboard) values ("singapore","Country","latin");
insert into words (word,description,keyboard) values ("slovakia","Country","latin");
insert into words (word,description,keyboard) values ("slovenia","Country","latin");
insert into words (word,description,keyboard) values ("solomon islands","Country","latin");
insert into words (word,description,keyboard) values ("somalia","Country","latin");
insert into words (word,description,keyboard) values ("south africa","Country","latin");
insert into words (word,description,keyboard) values ("spain","Country","latin");
insert into words (word,description,keyboard) values ("sri lanka","Country","latin");
insert into words (word,description,keyboard) values ("sudan","Country","latin");
insert into words (word,description,keyboard) values ("south sudan","Country","latin");
insert into words (word,description,keyboard) values ("suriname","Country","latin");
insert into words (word,description,keyboard) values ("swaziland","Country","latin");
insert into words (word,description,keyboard) values ("sweden","Country","latin");
insert into words (word,description,keyboard) values ("switzerland","Country","latin");
insert into words (word,description,keyboard) values ("syria","Country","latin");
insert into words (word,description,keyboard) values ("taiwan","Country","latin");
insert into words (word,description,keyboard) values ("tajikistan","Country","latin");
insert into words (word,description,keyboard) values ("tanzania","Country","latin");
insert into words (word,description,keyboard) values ("thailand","Country","latin");
insert into words (word,description,keyboard) values ("togo","Country","latin");
insert into words (word,description,keyboard) values ("tonga","Country","latin");
insert into words (word,description,keyboard) values ("trinidad and tobago","Country","latin");
insert into words (word,description,keyboard) values ("tunisia","Country","latin");
insert into words (word,description,keyboard) values ("turkey","Country","latin");
insert into words (word,description,keyboard) values ("turkmenistan","Country","latin");
insert into words (word,description,keyboard) values ("tuvalu","Country","latin");
insert into words (word,description,keyboard) values ("uganda","Country","latin");
insert into words (word,description,keyboard) values ("ukraine","Country","latin");
insert into words (word,description,keyboard) values ("united arab emirates","Country","latin");
insert into words (word,description,keyboard) values ("united kingdom","Country","latin");
insert into words (word,description,keyboard) values ("united states","Country","latin");
insert into words (word,description,keyboard) values ("uruguay","Country","latin");
insert into words (word,description,keyboard) values ("uzbekistan","Country","latin");
insert into words (word,description,keyboard) values ("vanuatu","Country","latin");
insert into words (word,description,keyboard) values ("vatican city","Country","latin");
insert into words (word,description,keyboard) values ("venezuela","Country","latin");
insert into words (word,description,keyboard) values ("vietnam","Country","latin");
insert into words (word,description,keyboard) values ("yemen","Country","latin");
insert into words (word,description,keyboard) values ("zambia","Country","latin");
insert into words (word,description,keyboard) values ("zimbabwe","Country","latin");
insert into words (word,description,keyboard) values ("alabama","US State","latin");
insert into words (word,description,keyboard) values ("alaska","US State","latin");
insert into words (word,description,keyboard) values ("arizona","US State","latin");
insert into words (word,description,keyboard) values ("arkansas","US State","latin");
insert into words (word,description,keyboard) values ("california","US State","latin");
insert into words (word,description,keyboard) values ("colorado","US State","latin");
insert into words (word,description,keyboard) values ("connecticut","US State","latin");
insert into words (word,description,keyboard) values ("delaware","US State","latin");
insert into words (word,description,keyboard) values ("florida","US State","latin");
insert into words (word,description,keyboard) values ("georgia","US State","latin");
insert into words (word,description,keyboard) values ("hawaii","US State","latin");
insert into words (word,description,keyboard) values ("idaho","US State","latin");
insert into words (word,description,keyboard) values ("illinois","US State","latin");
insert into words (word,description,keyboard) values ("indiana","US State","latin");
insert into words (word,description,keyboard) values ("iowa","US State","latin");
insert into words (word,description,keyboard) values ("kansas","US State","latin");
insert into words (word,description,keyboard) values ("kentucky","US State","latin");
insert into words (word,description,keyboard) values ("louisiana","US State","latin");
insert into words (word,description,keyboard) values ("maine","US State","latin");
insert into words (word,description,keyboard) values ("maryland","US State","latin");
insert into words (word,description,keyboard) values ("massachusetts","US State","latin");
insert into words (word,description,keyboard) values ("michigan","US State","latin");
insert into words (word,description,keyboard) values ("minnesota","US State","latin");
insert into words (word,description,keyboard) values ("mississippi","US State","latin");
insert into words (word,description,keyboard) values ("missouri","US State","latin");
insert into words (word,description,keyboard) values ("montana","US State","latin");
insert into words (word,description,keyboard) values ("nebraska","US State","latin");
insert into words (word,description,keyboard) values ("nevada","US State","latin");
insert into words (word,description,keyboard) values ("new hampshire","US State","latin");
insert into words (word,description,keyboard) values ("new jersey","US State","latin");
insert into words (word,description,keyboard) values ("new mexico","US State","latin");
insert into words (word,description,keyboard) values ("new york","US State","latin");
insert into words (word,description,keyboard) values ("namibia","US State","latin");
insert into words (word,description,keyboard) values ("north dakota","US State","latin");
insert into words (word,description,keyboard) values ("ohio","US State","latin");
insert into words (word,description,keyboard) values ("oklahoma","US State","latin");
insert into words (word,description,keyboard) values ("oregon","US State","latin");
insert into words (word,description,keyboard) values ("pennsylvania","US State","latin");
insert into words (word,description,keyboard) values ("rhode island","US State","latin");
insert into words (word,description,keyboard) values ("south carolina","US State","latin");
insert into words (word,description,keyboard) values ("south dakota","US State","latin");
insert into words (word,description,keyboard) values ("tennessee","US State","latin");
insert into words (word,description,keyboard) values ("texas","US State","latin");
insert into words (word,description,keyboard) values ("utah","US State","latin");
insert into words (word,description,keyboard) values ("vermont","US State","latin");
insert into words (word,description,keyboard) values ("virginia","US State","latin");
insert into words (word,description,keyboard) values ("washington","US State","latin");
insert into words (word,description,keyboard) values ("west virginia","US State","latin");
insert into words (word,description,keyboard) values ("wisconsin","US State","latin");
insert into words (word,description,keyboard) values ("wyoming","US State","latin");
